### ISSUE TITLE
Understanding cycle in dependencies

### ISSUE THREAD

**Issue by memsharded** [smoofra/fake-gcc-conan#1]
Hi @smoofra 

I am checking this, the build script the first thing it does is
```
conan export cc
```
Then the next step is creating the package
```
conan create libc
```
and ``libc`` has a ``tool_requires`` to ``cc`` compiler with ``self.tool_requires("cc/1.0", options={"libc": False})``

I understand that the ``libc=False`` option is there to break the cycle, and avoid the first ``cc`` to depend on ``libc``.
But still the binary for ``cc`` is not being built, only exported. Shouldn't the first command be ``conan create cc`` or something like that?

**Comment by smoofra** [comment]
The binary for cc gets created in the next line of the build script when it calls `conan create libc -pr:h ./Linux-x86_64 --build=missing`.    But doing `conan create cc -o libc=False ` first would be just as good.
